name: Test My Mail App

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v4
           
           - name: use node js
             uses: actions/setup-node@v4
             with:
                node-version: '22'

           - name: install dependency
             run: npm install
           
           - name: build
             run: npm run build 
             env: 
                MONGODB_URI: ${{ secrets.MONGODB_URI }} 
                JWT_SECRET: ${{secrets.JWT_SECRET}} 

           - name: All test end
             run: echo "All test end"